# Picko Daily Collector Runner
# Generated by setup_scheduler.ps1

$ProjectRoot = "C:\picko-scripts"
$VaultPath = "C:\picko-scripts\mock_vault"

# Set environment variables
$env:PICKO_VAULT_ROOT = $VaultPath
$env:OPENAI_API_KEY = (Get-ItemProperty -Path "HKCU:\Environment\").OPENAI_API_KEY

# Change to project directory
Set-Location $ProjectRoot

# Run daily collector
& $PythonPath -m scripts.daily_collector

# Log result
if ($LASTEXITCODE -eq 0) {
    Write-Output "[2026-02-15 05:50:28] Daily collector completed successfully" >> (Join-Path $ProjectRoot "logs\scheduler.log")
} else {
    Write-Output "[2026-02-DD 05:50:28] Daily collector failed with code $LASTEXITCODE" >> (Join-Path $ProjectRoot "logs\scheduler.log")
}
