# Windows Task Scheduler Setup Script for Picko
# This script creates a scheduled task to run daily_collector.py

param(
    [Parameter(Mandatory=$false)]
    [string]$VaultPath = "",

    [Parameter(Mandatory=$false)]
    [string]$PythonPath = "python",

    [Parameter(Mandatory=$false)]
    [string]$Hour = "8",

    [Parameter(Mandatory=$false)]
    [string]$Minute = "0",

    [Parameter(Mandatory=$false)]
    [switch]$WhatIf
)

# Script directory
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir

# Default vault path if not specified
if ([string]::IsNullOrEmpty($VaultPath)) {
    $VaultPath = Join-Path $env:USERPROFILE "Obsidian\PickoVault"
    Write-Host "No vault path specified, using default: $VaultPath" -ForegroundColor Yellow
}

# Task name
$TaskName = "Picko Daily Collector"

# PowerShell script to run
$ScheduledScriptPath = Join-Path $ProjectRoot "scripts\run_daily_collector.ps1"

# Create the runner script
$RunnerScript = @"
# Picko Daily Collector Runner
# Generated by setup_scheduler.ps1

`$ProjectRoot = "$ProjectRoot"
`$VaultPath = "$VaultPath"

# Set environment variables
`$env:PICKO_VAULT_ROOT = `$VaultPath
`$env:OPENAI_API_KEY = (Get-ItemProperty -Path "HKCU:\Environment\").OPENAI_API_KEY

# Change to project directory
Set-Location `$ProjectRoot

# Run daily collector
& `$PythonPath -m scripts.daily_collector

# Log result
if (`$LASTEXITCODE -eq 0) {
    Write-Output "[$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] Daily collector completed successfully" >> (Join-Path `$ProjectRoot "logs\scheduler.log")
} else {
    Write-Output "[$(Get-Date -Format 'yyyy-MM-DD HH:mm:ss')] Daily collector failed with code `$LASTEXITCODE" >> (Join-Path `$ProjectRoot "logs\scheduler.log")
}
"@

# Write runner script
$RunnerScriptPath = Join-Path $ProjectRoot "scripts\run_daily_collector.ps1"
$RunnerScript | Out-File -FilePath $RunnerScriptPath -Encoding UTF8

Write-Host "`n=== Picko Windows Task Scheduler Setup ===" -ForegroundColor Cyan
Write-Host "Project Root: $ProjectRoot"
Write-Host "Vault Path: $VaultPath"
Write-Host "Python: $PythonPath"
Write-Host "Schedule: $Hour`:$Minute (daily)"
Write-Host "Runner Script: $RunnerScriptPath`n"

if ($WhatIf) {
    Write-Host "[WHAT IF] Would create scheduled task '$TaskName'" -ForegroundColor Yellow
    Write-Host "[WHAT IF] Command: $RunnerScriptPath" -ForegroundColor Yellow
    exit 0
}

# Check if task already exists
$ExistingTask = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($ExistingTask) {
    Write-Host "Task '$TaskName' already exists." -ForegroundColor Yellow
    $Response = Read-Host "Do you want to replace it? (y/N)"
    if ($Response -ne 'y' -and $Response -ne 'Y') {
        Write-Host "Setup cancelled." -ForegroundColor Yellow
        exit 0
    }
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
    Write-Host "Removed existing task." -ForegroundColor Green
}

# Create scheduled task action
$Action = New-ScheduledTaskAction `
    -Execute "powershell.exe" `
    -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$RunnerScriptPath`""

# Create trigger (daily at specified time)
$Trigger = New-ScheduledTaskTrigger `
    -Daily `
    -At "$($Hour):$($Minute)"

# Create principal (run as current user)
$Principal = New-ScheduledTaskPrincipal `
    -UserId $env:USERNAME `
    -LogonType Interactive `
    -RunLevel Highest

# Register the task
try {
    Register-ScheduledTask `
        -TaskName $TaskName `
        -Action $Action `
        -Trigger $Trigger `
        -Principal $Principal `
        -Description "Picko Daily Content Collector - Automated RSS feed processing" `
        -ErrorAction Stop

    Write-Host "✓ Scheduled task created successfully!" -ForegroundColor Green
    Write-Host "`nTask Details:" -ForegroundColor Cyan
    Write-Host "  Name: $TaskName"
    Write-Host "  Schedule: Daily at $Hour`:$Minute"
    Write-Host "  Run as: $env:USERNAME"

    Write-Host "`nTo manually run the task:" -ForegroundColor Yellow
    Write-Host "  Start-ScheduledTask -TaskName `"$TaskName`""

    Write-Host "`nTo view task history:" -ForegroundColor Yellow
    Write-Host "  Get-ScheduledTaskInfo -TaskName `"$TaskName`""

    Write-Host "`nTo disable the task:" -ForegroundColor Yellow
    Write-Host "  Disable-ScheduledTask -TaskName `"$TaskName`""

    Write-Host "`nTo uninstall the task:" -ForegroundColor Yellow
    Write-Host "  Unregister-ScheduledTask -TaskName `"$TaskName`" -Confirm:`$false"

} catch {
    Write-Host "✗ Failed to create scheduled task: $_" -ForegroundColor Red
    exit 1
}

# Verify OPENAI_API_KEY is set
$ApiKey = [Environment]::GetEnvironmentVariable("OPENAI_API_KEY", "User")
if ([string]::IsNullOrEmpty($ApiKey)) {
    Write-Host "`n⚠ WARNING: OPENAI_API_KEY environment variable not set!" -ForegroundColor Yellow
    Write-Host "  Set it with:" -ForegroundColor Yellow
    Write-Host "  [Environment]::SetEnvironmentVariable('OPENAI_API_KEY', 'your-key-here', 'User')" -ForegroundColor Gray
} else {
    Write-Host "`n✓ OPENAI_API_KEY is configured" -ForegroundColor Green
}
