# Windows Task Scheduler Setup Script for Picko Workflows
# This script creates scheduled tasks to run workflow YAML files

param(
    [Parameter(Mandatory=$false)]
    [string]$WorkflowName = "daily_pipeline",

    [Parameter(Mandatory=$false)]
    [string]$VaultPath = "",

    [Parameter(Mandatory=$false)]
    [string]$PythonPath = "python",

    [Parameter(Mandatory=$false)]
    [string]$Hour = "8",

    [Parameter(Mandatory=$false)]
    [string]$Minute = "0",

    [Parameter(Mandatory=$false)]
    [ValidateSet("Daily", "Weekly", "Hourly")]
    [string]$Frequency = "Daily",

    [Parameter(Mandatory=$false)]
    [switch]$WhatIf
)

# Script directory
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir

# Default vault path if not specified
if ([string]::IsNullOrEmpty($VaultPath)) {
    $VaultPath = Join-Path $env:USERPROFILE "Obsidian\PickoVault"
    Write-Host "No vault path specified, using default: $VaultPath" -ForegroundColor Yellow
}

# Workflow path
$WorkflowPath = Join-Path $ProjectRoot "config\workflows\$WorkflowName.yml"

# Check if workflow exists
if (-not (Test-Path $WorkflowPath)) {
    Write-Host "ERROR: Workflow file not found: $WorkflowPath" -ForegroundColor Red
    Write-Host "Available workflows:" -ForegroundColor Yellow
    Get-ChildItem (Join-Path $ProjectRoot "config\workflows\*.yml") | ForEach-Object {
        Write-Host "  - $($_.BaseName)" -ForegroundColor Gray
    }
    exit 1
}

# Task name
$TaskName = "Picko Workflow - $WorkflowName"

# Create the runner script content
$RunnerScript = @"
# Picko Workflow Runner
# Auto-generated by setup_workflow_scheduler.ps1
# Workflow: $WorkflowName

`$ErrorActionPreference = "Stop"
`$ProjectRoot = "$ProjectRoot"
`$VaultPath = "$VaultPath"
`$WorkflowName = "$WorkflowName"

# Set environment variables
`$env:PICKO_VAULT_ROOT = `$VaultPath

# Load API keys from .env if exists
`$EnvFile = Join-Path `$ProjectRoot ".env"
if (Test-Path `$EnvFile) {
    Get-Content `$EnvFile | ForEach-Object {
        if (`$_ -match "^([^#][^=]+)=(.*)$") {
            `$name = `$matches[1].Trim()
            `$value = `$matches[2].Trim()
            [Environment]::SetEnvironmentVariable(`$name, `$value, "Process")
        }
    }
}

# Log function
function Write-Log {
    param([string]`$Message)
    `$Timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    `$LogEntry = "[`$Timestamp] `$Message"
    Write-Output `$LogEntry

    # Ensure logs directory exists
    `$LogsDir = Join-Path `$ProjectRoot "logs"
    if (-not (Test-Path `$LogsDir)) {
        New-Item -ItemType Directory -Path `$LogsDir -Force | Out-Null
    }

    # Append to workflow log
    `$LogFile = Join-Path `$LogsDir "workflow_`$WorkflowName.log"
    `$LogEntry | Out-File -FilePath `$LogFile -Append -Encoding UTF8
}

Write-Log "Starting workflow: `$WorkflowName"

# Change to project directory
Set-Location `$ProjectRoot

# Run workflow
try {
    `$Result = & `$PythonPath -m scripts.run_workflow --workflow "config\workflows\`$WorkflowName.yml" 2>&1
    `$ExitCode = `$LASTEXITCODE

    if (`$ExitCode -eq 0) {
        Write-Log "Workflow completed successfully"
        Write-Log `$Result
    } else {
        Write-Log "Workflow failed with exit code: `$ExitCode"
        Write-Log `$Result
    }
} catch {
    Write-Log "Workflow execution error: `$_"
    exit 1
}
"@

# Write runner script
$RunnerScriptPath = Join-Path $ProjectRoot "scripts\run_workflow_$WorkflowName.ps1"
$RunnerScript | Out-File -FilePath $RunnerScriptPath -Encoding UTF8

Write-Host "`n=== Picko Workflow Scheduler Setup ===" -ForegroundColor Cyan
Write-Host "Workflow: $WorkflowName"
Write-Host "Workflow Path: $WorkflowPath"
Write-Host "Project Root: $ProjectRoot"
Write-Host "Vault Path: $VaultPath"
Write-Host "Python: $PythonPath"
Write-Host "Schedule: $Frequency at $Hour`:$Minute"
Write-Host "Runner Script: $RunnerScriptPath`n"

if ($WhatIf) {
    Write-Host "[WHAT IF] Would create scheduled task '$TaskName'" -ForegroundColor Yellow
    Write-Host "[WHAT IF] Command: $RunnerScriptPath" -ForegroundColor Yellow
    exit 0
}

# Check if task already exists
$ExistingTask = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
if ($ExistingTask) {
    Write-Host "Task '$TaskName' already exists." -ForegroundColor Yellow
    $Response = Read-Host "Do you want to replace it? (y/N)"
    if ($Response -ne 'y' -and $Response -ne 'Y') {
        Write-Host "Setup cancelled." -ForegroundColor Yellow
        exit 0
    }
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
    Write-Host "Removed existing task." -ForegroundColor Green
}

# Create scheduled task action
$Action = New-ScheduledTaskAction `
    -Execute "powershell.exe" `
    -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$RunnerScriptPath`""

# Create trigger based on frequency
switch ($Frequency) {
    "Daily" {
        $Trigger = New-ScheduledTaskTrigger -Daily -At "$($Hour):$($Minute)"
    }
    "Weekly" {
        $Trigger = New-ScheduledTaskTrigger -Weekly -DaysOfWeek Monday,Tuesday,Wednesday,Thursday,Friday -At "$($Hour):$($Minute)"
    }
    "Hourly" {
        $Trigger = New-ScheduledTaskTrigger -Once -At (Get-Date) -RepetitionInterval (New-TimeSpan -Hours 1)
    }
}

# Create principal (run as current user)
$Principal = New-ScheduledTaskPrincipal `
    -UserId $env:USERNAME `
    -LogonType Interactive `
    -RunLevel Highest

# Register the task
try {
    Register-ScheduledTask `
        -TaskName $TaskName `
        -Action $Action `
        -Trigger $Trigger `
        -Principal $Principal `
        -Description "Picko Workflow: $WorkflowName - Automated content pipeline" `
        -ErrorAction Stop

    Write-Host "✓ Scheduled task created successfully!" -ForegroundColor Green
    Write-Host "`nTask Details:" -ForegroundColor Cyan
    Write-Host "  Name: $TaskName"
    Write-Host "  Schedule: $Frequency at $Hour`:$Minute"
    Write-Host "  Run as: $env:USERNAME"

    Write-Host "`nTo manually run the task:" -ForegroundColor Yellow
    Write-Host "  Start-ScheduledTask -TaskName `"$TaskName`""

    Write-Host "`nTo view task history:" -ForegroundColor Yellow
    Write-Host "  Get-ScheduledTaskInfo -TaskName `"$TaskName`""

    Write-Host "`nTo disable the task:" -ForegroundColor Yellow
    Write-Host "  Disable-ScheduledTask -TaskName `"$TaskName`""

    Write-Host "`nTo uninstall the task:" -ForegroundColor Yellow
    Write-Host "  Unregister-ScheduledTask -TaskName `"$TaskName`" -Confirm:`$false"

} catch {
    Write-Host "✗ Failed to create scheduled task: $_" -ForegroundColor Red
    exit 1
}

# List available workflows
Write-Host "`n=== Available Workflows ===" -ForegroundColor Cyan
Get-ChildItem (Join-Path $ProjectRoot "config\workflows\*.yml") | ForEach-Object {
    $wfName = $_.BaseName
    $isActive = if ($wfName -eq $WorkflowName) { " (active)" } else { "" }
    Write-Host "  - $wfName$isActive" -ForegroundColor Gray
}
